name: C++ Component CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  release:
    types: [published]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup Bazel
      uses: bazelbuild/setup-bazelisk@v2
    
    - name: Cache Bazel
      uses: actions/cache@v3
      with:
        path: |
          ~/.cache/bazel
        key: ${{ runner.os }}-bazel-cpp-${{ hashFiles('.bazelversion', '.bazelrc', 'MODULE.bazel') }}
        restore-keys: |
          ${{ runner.os }}-bazel-cpp-
    
    - name: Build library
      run: bazel build //src:math_operations
    
    - name: Build all targets
      run: bazel build //...
    
    - name: Run all tests
      run: bazel test //... --test_output=errors
    
    - name: Validate module structure
      run: |
        echo "Validating Bazel module structure..."
        bazel query //... --output=package
        
    - name: Check code formatting (if clang-format available)
      run: |
        if command -v clang-format &> /dev/null; then
          find src tests -name "*.cpp" -o -name "*.h" | xargs clang-format --dry-run --Werror
        else
          echo "clang-format not available, skipping format check"
        fi

  trigger-renovate:
    needs: build-and-test
    runs-on: ubuntu-latest
    if: github.event_name == 'release'
    
    steps:
    - name: Trigger Renovate update in meta-repo
      run: |
        VERSION="${{ github.event.release.tag_name }}"
        echo "Triggering Renovate update for new version: $VERSION"
        
        # Extract version number (remove 'v' prefix if present)
        VERSION_NUMBER="${VERSION#v}"
        
        # Create a release note that Renovate will pick up
        echo "Component hbf_examplecpp updated to version $VERSION_NUMBER"
        echo "Release URL: ${{ github.event.release.html_url }}"
        
        # Optional: Force Renovate run in meta-repo (if RENOVATE_WEBHOOK_SECRET is configured)
        if [ -n "${{ secrets.RENOVATE_WEBHOOK_SECRET }}" ]; then
          curl -X POST \
            -H "Authorization: token ${{ secrets.META_REPO_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            "https://api.github.com/repos/thetanil/hbf/dispatches" \
            -d '{
              "event_type": "renovate-trigger",
              "client_payload": {
                "component": "hbf_examplecpp",
                "version": "'$VERSION_NUMBER'",
                "repository": "thetanil/hbf-examplecpp",
                "release_url": "${{ github.event.release.html_url }}"
              }
            }'
        fi
